import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/contexts/AuthContext";
import TopBar from "@/components/TopBar/TopBar";
import Footer from "@/components/shared/Footer/Footer";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PetBrbV2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <TopBar />
          <main className={styles.main}>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}